spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db1
    username: user1
    password: user1
    driver-class-name: com.mysql.jdbc.Driver
  db2-datasource:
    url: jdbc:mysql://localhost:3306/db2
    username: user2
    password: user2
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    #properties.hibernate.format_sql: true


#logging.level.org.hibernate.SQL: debug
logging.level.org.hibernate.type.descriptor.sql: trace
#logging.level.org.hibernate.type.descriptor.sql.BasicExtractor: trace
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder: trace

# JPA Transaction log
logging.level.org.springframework.orm.jpa: DEBUG
logging.level.org.springframework.orm.jpa.JpaTransactionManager: INFO
logging.level.org.springframework.orm.jpa.SharedEntityManagerCreator: INFO
logging.level.org.springframework.transaction: DEBUG
logging.level.org.springframework.transaction.interceptor.NameMatchTransactionAttributeSource: INFO
logging.level.org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG
